--- a/.github/workflows/build_windows.yml
+++ b/.github/workflows/build_windows.yml
@@ -156,4 +156,4 @@
             artifact/*.sha512sum
           compression-level: 0
           retention-days: 3
-          if-no-files-found: error
+          if-no-files-found: error