on: push
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-4-dev build-essential
            pkg-config --exists gtk4
            cargo clippy --all-targets --all-features
